# Generated by Django 4.1.7 on 2023-03-22 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuarios',
            table='usuario_usuarios',
        ),
    ]
