# Generated by Django 4.1.7 on 2023-03-22 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuarios_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuarios',
            table=None,
        ),
    ]
