# Generated by Django 4.1.7 on 2023-03-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuarios_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
